# Generated by Django 2.0.1 on 2018-01-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repicimages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='SubredditsList',
        ),
    ]
