# Generated by Django 2.0.1 on 2018-01-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('url', models.TextField(max_length=2000)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
