# Generated by Django 2.0.1 on 2018-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('mp4', models.CharField(max_length=200, null=True)),
                ('nsfw', models.IntegerField(null=True)),
                ('sitetag', models.CharField(max_length=15)),
                ('created', models.DateTimeField()),
                ('subreddit', models.CharField(max_length=20)),
                ('subredditid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubredditsList',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('subreddit', models.CharField(max_length=30)),
                ('nsfw', models.IntegerField(null=True)),
            ],
        ),
    ]
