# Generated by Django 2.0.1 on 2018-01-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='mp4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='nsfw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='sitetag',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
