# Generated by Django 2.0.1 on 2018-01-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20180118_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubredditsList',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('subreddit', models.CharField(max_length=30)),
                ('nsfw', models.IntegerField(null=True)),
            ],
        ),
    ]
